--
-- Script was generated by Devart dbForge Studio 2019 for MySQL, Version 8.1.22.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 2025.10.12. 15:10:06
-- Server version: 5.7.44
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

DROP DATABASE IF EXISTS hangszerek;

CREATE DATABASE IF NOT EXISTS hangszerek
	CHARACTER SET utf8
	COLLATE utf8_hungarian_ci;

--
-- Set default database
--
USE hangszerek;

--
-- Create table `instruments`
--
CREATE TABLE IF NOT EXISTS instruments (
  id INT(11) NOT NULL AUTO_INCREMENT,
  name VARCHAR(255) DEFAULT NULL,
  description TEXT DEFAULT NULL,
  brand VARCHAR(255) DEFAULT NULL,
  price INT(11) DEFAULT NULL,
  quantity INT(11) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 7,
AVG_ROW_LENGTH = 2730,
CHARACTER SET utf8,
COLLATE utf8_hungarian_ci;

-- 
-- Dumping data for table instruments
--
INSERT INTO instruments VALUES
(1, 'American Original 50s Telecaster', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam scelerisque, justo id dapibus convallis, est sapien consequat nibh, ut tristique tellus magna a mi. Vestibulum interdum orci non lectus tincidunt dictum. Etiam facilisis orci a elit facilisis, ac pretium velit dictum. Pellentesque eu auctor diam. Curabitur suscipit leo eu sollicitudin venenatis.', 'Fender', 649900, 1),
(2, 'Troublemaker Telecaster', 'Quisque vel tellus nec leo vestibulum molestie. Donec fringilla urna non erat dictum posuere. Nullam luctus convallis facilisis. Praesent elementum varius metus sit amet elementum. Praesent vitae leo non sapien rutrum elementum. Aenean eget hendrerit turpis. Morbi in sagittis quam, varius finibus nisi. Sed eu mi malesuada, semper felis eu, rutrum tellus. Quisque rutrum id dui vitae luctus. Praesent vehicula cursus mollis.', 'Fender', 469990, 3),
(3, 'PM-2 Standard Parlor, Natural', 'Nulla mollis arcu magna. Mauris ac commodo turpis, eget placerat ligula. Suspendisse potenti. Nullam congue nisi at quam interdum, eget consectetur sem ultricies. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Vestibulum scelerisque risus mi, eget lacinia purus sagittis in. Suspendisse blandit eu est a placerat.', 'Fender', 217500, 8),
(4, 'Steve Vai Signature JEM77 - Blue Floral Pattern', 'Nunc lorem lacus, commodo a eros a, venenatis eleifend nunc. Pellentesque interdum, odio tincidunt aliquam aliquam, velit nulla tempus tortor, non tempus mi turpis ut risus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Vivamus vitae aliquet arcu. Sed pretium, ipsum sed sagittis tempus, magna ligula sollicitudin massa, mollis suscipit arcu arcu sed est. Nam eleifend dui ante, sit amet ultrices dui laoreet ac.', 'Ibanez', 474775, 2),
(5, 'J Custom RG8560 Electric Guitar - Sapphire Blue', 'Vivamus eu purus luctus, porta orci et, gravida nulla. Duis elementum lacus eu arcu ullamcorper tincidunt. Integer quis sem et ante mollis finibus vitae et nunc. Sed porttitor interdum ipsum, sit amet varius dui convallis non. Mauris lobortis erat ac urna dictum mollis. Nam luctus urna quis erat venenatis, imperdiet dapibus est sodales. Fusce ornare consequat felis, eu accumsan erat vulputate quis. Donec suscipit consequat mi quis posuere. Donec nulla augue, imperdiet sed orci at, tristique pretium ipsum. Mauris a lacus mauris. Integer pretium fringilla lacus vitae dignissim.', 'Ibanez', 892800, 1),
(6, 'Viper-1000 - See Thru Black Cherry Satin', 'Vivamus eu purus luctus, porta orci et, gravida nulla. Duis elementum lacus eu arcu ullamcorper tincidunt. Integer quis sem et ante mollis finibus vitae et nunc. Sed porttitor interdum ipsum, sit amet varius dui convallis non. Mauris lobortis erat ac urna dictum mollis. Nam luctus urna quis erat venenatis, imperdiet dapibus est sodales.', 'ESP LTD', 329000, 4);

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;